DROP DATABASE IF EXISTS tienda;

CREATE DATABASE tienda;

USE tienda;

CREATE TABLE cliente(
	id INT(11) PRIMARY KEY AUTO_INCREMENT,
    nombre VARCHAR(50) NOT NULL,
    apellidos VARCHAR(100) NOT NULL,
    genero CHAR(1) NOT NULL,
    direccion VARCHAR(100) NOT NULL,
    codpostal CHAR(5) NOT NULL,
    poblacion VARCHAR(100) NOT NULL,
    provincia VARCHAR(100) NOT NULL,
    password CHAR(40) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE KEY,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE usuario(
    id INT(11) PRIMARY KEY AUTO_INCREMENT,
    email VARCHAR(100) NOT NULL UNIQUE KEY,
    password CHAR(40) NOT NULL,
    rol TINYINT(4) NOT NULL,
    nombre VARCHAR(50) NOT NULL,
    creado TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE producto(
    cod CHAR(5) PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    tipo TINYINT
);